### ISSUE TITLE
Mention that interactable actors need collision boxes

### ISSUE THREAD

**Issue by brno32** [twistedbytes-net/TBIA-Documentation#18]
The documentation doesn't spell out what collision boxes an actor needs. I had to add a box collision to one of my actors to make it interactable. I think these steps should be a wee bit more specific in the `create-your-first-interactable-object` and the `interactable-actor` sections

**Comment by andgeno** [comment]
Thank you for your suggestion! We incorporated it into the next iteration of the documentation pages.
